### ISSUE TITLE
CellMatch db w/ singleR

### ISSUE THREAD

**Issue by raveancic** [ZJUFanLab/scCATCH_performance_comparison#1]
Hi, very interesting tool and great effort, congratulations, I can't wait to use it!
 
I was wondering if it is available a tutorial/code for the creation of the lists generated from CellMatch database using the marker genes of mouse/human cells in order to use CellMatch ref db with SingleR or other tools. Unfortunately from the codes available here I see that these list / objects (i.e. marker genes of mouse kidney cells) have been previously created and I do not find any hint on how to create them. 

Thank you very much and thank you in advance for the clarification, maybe I am missing something.

Best,
Alessandro

**Comment by ZJUFanLab** [comment]
Hi,  sorry for this late reply to your message. I don't fully understand your question. Do you mean how to use CellMatch db for other methods?

**Comment by raveancic** [comment]
Hello, yes, I meant if it was possible use the CellMatch db with with singleR tool, and how to use it.
Thank you very much in advance.
Alessandro

**Comment by ZJUFanLab** [comment]
Hello, CellAssign, garnett, scMap and SingleR are all reference-dependent methods. CellAssign and garnett are based on markers, while scMap and SingleR are based on RNA-seq profiles as default.
As we tried to compare the performance of various methods by avoiding the effect of various reference, so we used CellMatch to construct the common reference for them. Because the CellAssign requires the reference of markers as a binary matrix wherein the column represents the cell type and the row represents marker gene. If the cell type have the marker gene in CellMatch,  then the value in the reference matrix will be set as 1. If not, then set it as 0. Similarly, we used this binary reference matrix as the reference for SingleR. As the example of mouse kidney below.

```
# Creating a new reference data set
celltypes <- colnames(mouse_kidney_markers)
cellmaintypes <- colnames(mouse_kidney_markers)
mouse_kidney_ref <- list(name = 'CellMatch',data = as.matrix(mouse_kidney_markers),
                        types = celltypes,main_types = cellmaintypes)
mouse_kidney_ref$de.genes <- CreateVariableGeneSet(as.matrix(mouse_kidney_markers),celltypes,200)
mouse_kidney_ref$de.genes.main <- CreateVariableGeneSet(as.matrix(mouse_kidney_markers),cellmaintypes,300)
```

Hope my suggestions will be helpful to you.

**Comment by raveancic** [comment]
Thank you very much for this, you have been very clear.
Just to be sure if I understood well then, I have ~53 K breast cancer pbmc of mouse in a seurat object, I will run the following command

```
library(scCATCH)

clu_markers <- findmarkergenes(seurat_integrated,
                               species = "Mouse",
                               match_CellMatch = T,
                               cancer = "Breast",
                               tissue = "Blood-related")

```
 Then I will have my clu_markers from which I can create the list you mentioned above and I can use either with SingleR or with CellAnnotation. 
Thank you in advance!

**Comment by ZJUFanLab** [comment]
Hello, if you want to use SingleR to annotate your breast cancer pbmc, you can download scRNA-seq profiles from  [MCA](https://www.ncbi.nlm.nih.gov/pubmed/29474909) as the reference by selecting the tissue of peripheral blood because SingleR is RNA-seq-dependent annotating method. But MCA only have normal cells. If your pbmc data contains cancer cells like CTCs, MCA is not able to find them out.

Indeed, CellMatch contains normal cell and cancer cell markers. If you want to build a binary reference for SingleR, you can download the [cellmatch.rds](https://github.com/ZJUFanLab/scCATCH_performance_comparison/blob/master/cellmatch.rds) directly and select the tissue of your interest (peripheral blood,blood, breast or breast cancer, etc.) to build it yourself because `findmarkergenes` is to find poteintal highly expressed gene for pre-clustered cells and the `clu_markers` generated from `findmarkergenes` does not contain the information of cell types, it only contains the marker genes for each cluster.

Besides, the tissue type in `findmarkergenes` should be more specific. You can refer the usage of [scCATCH](https://github.com/ZJUFanLab/scCATCH). For example:
```
clu_markers <- findmarkergenes(seurat_integrated,
                               species = "Mouse",
                               match_CellMatch = T,
                               cancer = "Breast Cancer",
                               tissue = "Breast")

clu_markers <- findmarkergenes(seurat_integrated,
                               species = "Mouse",
                               match_CellMatch = T,
                               tissue = c("Breast","Peripheral blood","Mammary epithelium"))

clu_markers <- findmarkergenes(seurat_integrated,
                               species = "Mouse",
                               match_CellMatch = T,
                               tissue = c("Blood","Peripheral blood"))
``` 

But I strongly suggest you to find another RNA-seq data (bulk or single-cell) of breast cancer-related pbmc samples from literautre that have been published as the reference for SingleR if there are normal cells and cancer cells in your `seurat_integrated` data.

**Comment by raveancic** [comment]
Thank you very much you have been very kind and very helpful. I will use MCA  with SingleR because I am not interested in CTC and they should be very few. Meanwhile I will also run scCATCH to build a binary matrix for both SingleR and CellAssign. 

Thank you again!
Alessandro

**Comment by zznx** [comment]
hello，I can't download cellmatch.rds, how can I fix it?thank you

Thank you very much!   @ZJUFanLab
